name: 'GitHub Actions Usage Calculator'
description: 'Calculating GitHub Actions processing time'
inputs:
  repo:
    description: 'repo-owner/repository-name'
    required: true
  start-date:
    description: 'Start date of calculate range'
    required: true
  end-date:
    description: 'End date of calculate range'
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - --repo ${{ inputs.repo }}
    - --start ${{ inputs.start-date }}
    - --end ${{ inputs.end-date }}
branding:
  icon: clock
  color: blue
