name: Update Major Version

on:
  push:
    tags: 'v[0-9].[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  update-major-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haya14busa/action-update-semver@fb48464b2438ae82cc78237be61afb4f461265a1
        with:
          major_version_tag_only: true
